spring.application.name=springdatathemleafshopping
# ===== DataSource (MariaDB) =====
spring.datasource.url=jdbc:mariadb://localhost:3308/votrieuan_shopdb?useSsl=false
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
server.port=8081

# HikariCP (tu? ch?n)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=600000

# ===== JPA / Hibernate =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.platform=mariadb
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

# = thymeleaf Config
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# server.port=8080
